# Generated by Django 4.2.29 on 2026-04-01 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_timetable_timetableevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_at', models.DateTimeField()),
                ('email_sent', models.BooleanField(default=False)),
                ('popup_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.student')),
                ('timetable_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.timetableevent')),
            ],
        ),
    ]
