# Generated by Django 4.2.29 on 2026-04-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='timetableevent',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='title',
            field=models.CharField(default='My Timetable', max_length=200),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='uploaded_file_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
